using UnityEngine;
using TMPro;
using UnityEngine.UI;
using UnityEngine.InputSystem;

public class invToolTip : MonoBehaviour
{
    public static invToolTip Instance { get; private set; }

    [Header("UI Components")]
    [SerializeField] private TextMeshProUGUI titleText;
    [SerializeField] private TextMeshProUGUI typeText;
    [SerializeField] private TextMeshProUGUI descriptionText;
    [SerializeField] private Image iconImage;

    [Header("Background Settings")]
    [SerializeField] private RectTransform backgroundRect;

    [Header("Dynamic Scaling Settings")]
    [SerializeField] private float baseHeight = 80f;   // The minimum height of the box
    [SerializeField] private float heightPerLine = 25f; // Add this much per line found

    private void Awake()
    {
        if (Instance == null) Instance = this;
        else Destroy(gameObject);
    }

    private void Start() => gameObject.SetActive(false);

    private void Update()
    {
        if (gameObject.activeSelf)
            transform.position = Mouse.current.position.ReadValue();
    }

    public void ShowToolTip(ItemData item)
    {
        if (item == null) return;

        titleText.text = $"<size=120%>{item.itemName}</size>";
        typeText.text = $"<size=90%>{item.itemType}</size>";
        descriptionText.text = $"<size=80%>{GenerateDescription(item)}</size>";

        iconImage.gameObject.SetActive(item.icon != null);
        if (item.icon != null) iconImage.sprite = item.icon;

        gameObject.SetActive(true);

        // Force update to get accurate line counts
        Canvas.ForceUpdateCanvases();

        // 1. Get the actual number of lines generated by the text (including wraps)
        int totalLines = descriptionText.textInfo.lineCount;

        // 2. Calculate height based on lines, not just a sum of heights
        // This makes it feel consistent regardless of how long or short the text is
        float calculatedHeight = baseHeight + (totalLines * heightPerLine);

        Debug.Log($"[ToolTip Debug] Lines: {totalLines} | Calculated Height: {calculatedHeight}");

        if (backgroundRect != null)
        {
            backgroundRect.sizeDelta = new Vector2(backgroundRect.sizeDelta.x, calculatedHeight);
        }
    }

    public void HideToolTip() => gameObject.SetActive(false);

    private string GenerateDescription(ItemData item)
    {
        string desc = "";
        if (item is UseableItem u && u.abilityToExecute != null)
        {
            if (u.abilityToExecute is IItemDescriptionProvider p) desc += p.GetDetailedDescription();
            else
            {
                if (u.abilityToExecute is offensiveRanged r) desc += $"Damage: {r.damage}\n";
                desc += $"Use Rate: {u.useRate}s\n";
            }
        }
        else if (item is IItemDescriptionProvider ip) desc += ip.GetDetailedDescription();

        desc += item.IsUnbreakable ? "\nUnbreakable" : $"\nDurability: {item.maxDurability}";
        return desc;
    }
}